export const CATEGORIES = [
  { value: 1, name: 'Arts & Culture' },
  { value: 2, name: 'Career & Business' },
  { value: 3, name: 'Cars & Motorcycles' },
  { value: 4, name: 'Community & Environment' },
  { value: 5, name: 'Dancing' },
  { value: 6, name: 'Education & Learning' },
  { value: 8, name: 'Fashion & Beauty' },
  { value: 9, name: 'Fitness' },
  { value: 10, name: 'Food & Drink' },
  { value: 11, name: 'Games' },
  { value: 12, name: 'LGBT' },
  { value: 13, name: 'Movements & Politics' },
  { value: 14, name: 'Health & Wellbeing' },
  { value: 15, name: 'Hobbies & Crafts' },
  { value: 16, name: 'Language & Ethnic Identity' },
  { value: 17, name: 'Lifestyle' },
  { value: 18, name: 'Book Clubs' },
  { value: 20, name: 'Movies & Film' },
  { value: 21, name: 'Music' },
  { value: 22, name: 'New Age & Spirituality' },
  { value: 23, name: 'Outdoors & Adventure' },
  { value: 24, name: 'Paranormal' },
  { value: 25, name: 'Parents & Family' },
  { value: 26, name: 'Pets & Animals' },
  { value: 27, name: 'Photography' },
  { value: 28, name: 'Religion & Beliefs' },
  { value: 29, name: 'Sci-Fi & Fantasy' },
  { value: 30, name: 'Singles' },
  { value: 31, name: 'Socializing' },
  { value: 32, name: 'Sports & Recreation' },
  { value: 33, name: 'Support' },
  { value: 34, name: 'Tech' },
  { value: 36, name: 'Writing' }
];
